services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.ui
    image: nginx
    container_name: nginx
    ports:
      - "80:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: api
    container_name: api
    ports:
      - "8080:8080"