# Generated by Django 5.2.6 on 2025-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_alter_game_playertwo"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="password",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
    ]
