# Generated by Django 5.2.6 on 2025-09-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_game_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="ended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="turn",
            field=models.IntegerField(default=1),
        ),
    ]
