# Generated by Django 5.2.6 on 2025-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_game_ended_game_turn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="password",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
