# Generated by Django 5.2.6 on 2025-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_alter_game_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
