# Generated by Django 5.2.6 on 2025-09-19 07:55

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_next_game_previous_alter_game_playerone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(default=game.models.default_board),
        ),
    ]
