FROM python:3.13.3-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-openbsd libpq5 && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv / uvx /bin/

COPY ./pyproject.toml .

RUN uv pip install . --system --no-deps

COPY . .

RUN chmod +x test.sh

ENTRYPOINT [ "./start.sh" ]