server {
    listen 80;
    server_name api.test.com;
    
    location / {
        proxy_pass http://django:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
server {
    listen 80;
    server_name www.test.com;
    
    location / {
        proxy_pass http://host.docker.internal:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}